### ISSUE TITLE
Proper nouns that might benefit form a <span xml:lang="LANGUAGE"> tag

### ISSUE THREAD

**Issue by thewchan** [weijia-cheng/emma-goldman_my-disillusionment-in-russia#5]
`Beloöstrov`
`Gulyai-Poleh`
`Makhno`
`Belo-Ostrov`
`Schlüsselburg`
`Tchernishevsky`
`Tsiperovitch`
`Pouget`
`Pataud`
`Nevsky Prospekt`
`Delovoi Dvor`
`Makhnovtsi`
`Thiers`
`Gallifet`
`Veh-Tcheka`
`Tverskaya`
`Makhnovstchina`
`Mratchny`

**Comment by thewchan** [comment]
`chapter-28.xhtml` line 51
`<i xml:lang="ru-Latn">Ossoby Otdel</i>`
Seems to be a proper noun, might not need italics? If it does it might be missing semantics.

**Comment by weijia-cheng** [comment]
I think the names in the first comment don't need semantics since I don't think they have any real chance of being mispronounced as English words. (See [8.2.9.2](https://standardebooks.org/manual/1.6.2/8-typography#8.2.9.2).) I am not entirely sure about "Ossoby Otdel" since I guess it is a proper name but I think it's also the Russian for "Special Department." I'll check with Alex about how to handle such cases.

Edit: Actually, the rule seems clear enough. Seems like it should not be italicized.
